name: LLVM Leech CI Exploit
on: [push]

jobs:
  build-and-exploit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install LLVM/Clang (official version)
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100
          sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-18 100
          sudo update-alternatives --install /usr/bin/opt opt /usr/bin/opt-18 100
          sudo apt install cmake -y

      - name: Build LLVM Pass (.so from .cpp)
        run: |
          mkdir -p build
          cd build
          cmake ../src
          make

      - name: Verify shared object exists (corrected path)
        run: |
          test -f build/inject_payload_pass.so && echo "Shared library compiled successfully" || \
          test -f inject_payload_pass.so && echo "Shared library compiled successfully" || \
          (echo "Compilation failed - shared library not found" && exit 1)

      - name: Compile infected target with LLVM Pass
        run: |
          clang -flegacy-pass-manager \
            -Xclang -load -Xclang ./build/inject_payload_pass.so \
            src/infected_target.c -o infected_target
          chmod +x infected_target
          ./infected_target
