name: Weaponized LLVM Leech CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install LLVM & curl
      run: |
        sudo apt update
        sudo apt install -y llvm clang curl

    - name: Build LLVM Injection Plugin
      run: |
        cd src
        clang -shared -fPIC -o leech_pass.so inject_payload_pass.cpp `llvm-config --cxxflags --ldflags --system-libs --libs all`

    - name: Compile Infected Binary
      run: |
        cd src
        clang -Xclang -load -Xclang ./leech_pass.so -Xclang -add-plugin -Xclang inject_payload infected_target.c leech_payload.c -o infected_app

    - name: Execute Infected Binary
      run: |
        ./src/infected_app
