name: LLVM Leech CI Exploit
on: [push]

jobs:
  build-and-exploit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup official LLVM/Clang (latest stable)
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18  # installs LLVM/Clang 18
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100
          sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-18 100
          sudo update-alternatives --install /usr/bin/opt opt /usr/bin/opt-18 100
          sudo apt install cmake -y

      - name: Verify Clang Version
        run: |
          clang --version
          opt --version

      - name: Build LLVM Pass (inject_payload_pass.so)
        run: |
          mkdir -p build
          cd build
          cmake ../src
          make

      - name: Compile infected target with LLVM Pass
        run: |
          cd build
          clang -flegacy-pass-manager \
            -Xclang -load -Xclang ./inject_payload_pass.so \
            ../src/infected_target.c -o infected_target
          chmod +x infected_target
          ./infected_target
