name: LLVM Leech CI Exploit
on: [push]

jobs:
  build-and-exploit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup LLVM Environment
        run: |
          sudo apt update
          sudo apt install llvm clang cmake -y

      - name: Build LLVM Pass (inject_payload_pass.so)
        run: |
          mkdir -p build
          cd build
          cmake ../src
          make

      - name: Compile infected target with LLVM Pass
        run: |
          cd build
          clang -flegacy-pass-manager \
            -Xclang -load -Xclang ./inject_payload_pass.so \
            ../src/infected_target.c -o infected_target
          chmod +x infected_target
          ./infected_target